#! /bin/sh

sxhkd &
setxkbmap es &
wmname LG3D &
feh --bg-fill --randomize ~/Pictures/background/* &

picom --config /home/jack/.config/compton/compton.conf &

$HOME/.config/polybar/launch.sh &

bspc monitor -d WEB WEB TTY TTY LAB LAB VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a ksnip state=floating 
bspc rule -a cherrytree desktop='^5'
bspc rule -a burp-StartBurp state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
